
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  datasource:
    name: test
#    name: weiwei
    url: jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://47.120.4.169:3306/weiwei?useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    username: weiwei
#    password: HFyZ4RJTW7sYXjeP
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000   # 数据库连接超时时间,默认30秒,即30000
      validation-timeout: 3000    # 指定验证连接有效性的超时时间(默认是5秒,最小不能小于250毫秒)
      idle-timeout: 60000         # 空闲连接超时时间,一个连接idle状态的最大时长（毫秒）,超时则被释放（retired）,默认是10分钟,只有空闲连接数大于最大连接数且空闲时间超过该值,才会被释放
      login-timeout: 5            # 指定连接数据库的超时时间,单位:秒
      max-lifetime: 70000         # 指定连接池中连接的最大生存时间,单位:毫秒.默认是1800000,即30分钟
      maximum-pool-size: 30       # 指定连接池最大的连接数,包括使用中的和空闲的连接,默认值10
      minimum-idle: 10            # 指定连接维护的最小空闲连接数,当使用HikariCP时指定
      read-only: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean

#操作oss需要的一些参数
#aliyun:
#  oss:
#    accessKeyId: LTAI5t6r23uBpPNcsUp1Vzt5 # 阿里云的accessKeyId
#    accessKeySecret: Y6LSQA0cRFf7jzkT6dsDijOeB1yTYZ    # accessKey 密码
#    endpoint: oss-cn-shenzhen.aliyuncs.com
#    bucketName: my-photos-ts   # bucket 名称
#    policy:
#      expire: 300 # 签名有效期(S)
#    maxSize: 10 # 上传文件大小(M)
#    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
#    dir:
#      prefix: https://my-photos-ts.oss-cn-shenzhen.aliyuncs.com/image/ # 上传文件夹路径前缀

oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI5t6r23uBpPNcsUp1Vzt5
  accessKeySecret: Y6LSQA0cRFf7jzkT6dsDijOeB1yTYZ
  bucketName: my-photos-ts
server:
  port: 7070

resourcesPath: src/main/resources/uploadFile